name: bunny_befuddle
description: "An isometric platformer game where a bunny collects carrots."
publish_to: "none"
version: 0.0.3+1

environment:
  sdk: ^3.8.0

dependencies:
  flame: ^1.29.0
  flame_audio: ^2.11.6
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^8.0.0

flutter:
  assets:
    - assets/images/
    - assets/audio/
